# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unforgetable.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unforgetable.proto',
  package='unforgetable',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12unforgetable.proto\x12\x0cunforgetable\"\x1e\n\x0crequestType1\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\".\n\x0crequestType2\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x02\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x02\"\x1d\n\x0breturnType1\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\"-\n\x0breturnType2\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x02\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x02\x32\x96\x01\n\x08Service1\x12\x44\n\tfunction1\x12\x1a.unforgetable.requestType1\x1a\x19.unforgetable.returnType1\"\x00\x12\x44\n\tfunction2\x12\x1a.unforgetable.requestType2\x1a\x19.unforgetable.returnType2\"\x00\x32\x96\x01\n\x08Service2\x12\x44\n\tfunction1\x12\x1a.unforgetable.requestType1\x1a\x19.unforgetable.returnType2\"\x00\x12\x44\n\tfunction2\x12\x1a.unforgetable.requestType2\x1a\x19.unforgetable.returnType1\"\x00\x62\x06proto3'
)




_REQUESTTYPE1 = _descriptor.Descriptor(
  name='requestType1',
  full_name='unforgetable.requestType1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='unforgetable.requestType1.field1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_REQUESTTYPE2 = _descriptor.Descriptor(
  name='requestType2',
  full_name='unforgetable.requestType2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='unforgetable.requestType2.field1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field2', full_name='unforgetable.requestType2.field2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=114,
)


_RETURNTYPE1 = _descriptor.Descriptor(
  name='returnType1',
  full_name='unforgetable.returnType1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='unforgetable.returnType1.field1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=145,
)


_RETURNTYPE2 = _descriptor.Descriptor(
  name='returnType2',
  full_name='unforgetable.returnType2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='unforgetable.returnType2.field1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field2', full_name='unforgetable.returnType2.field2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['requestType1'] = _REQUESTTYPE1
DESCRIPTOR.message_types_by_name['requestType2'] = _REQUESTTYPE2
DESCRIPTOR.message_types_by_name['returnType1'] = _RETURNTYPE1
DESCRIPTOR.message_types_by_name['returnType2'] = _RETURNTYPE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

requestType1 = _reflection.GeneratedProtocolMessageType('requestType1', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTYPE1,
  '__module__' : 'unforgetable_pb2'
  # @@protoc_insertion_point(class_scope:unforgetable.requestType1)
  })
_sym_db.RegisterMessage(requestType1)

requestType2 = _reflection.GeneratedProtocolMessageType('requestType2', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTYPE2,
  '__module__' : 'unforgetable_pb2'
  # @@protoc_insertion_point(class_scope:unforgetable.requestType2)
  })
_sym_db.RegisterMessage(requestType2)

returnType1 = _reflection.GeneratedProtocolMessageType('returnType1', (_message.Message,), {
  'DESCRIPTOR' : _RETURNTYPE1,
  '__module__' : 'unforgetable_pb2'
  # @@protoc_insertion_point(class_scope:unforgetable.returnType1)
  })
_sym_db.RegisterMessage(returnType1)

returnType2 = _reflection.GeneratedProtocolMessageType('returnType2', (_message.Message,), {
  'DESCRIPTOR' : _RETURNTYPE2,
  '__module__' : 'unforgetable_pb2'
  # @@protoc_insertion_point(class_scope:unforgetable.returnType2)
  })
_sym_db.RegisterMessage(returnType2)



_SERVICE1 = _descriptor.ServiceDescriptor(
  name='Service1',
  full_name='unforgetable.Service1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=195,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='function1',
    full_name='unforgetable.Service1.function1',
    index=0,
    containing_service=None,
    input_type=_REQUESTTYPE1,
    output_type=_RETURNTYPE1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='function2',
    full_name='unforgetable.Service1.function2',
    index=1,
    containing_service=None,
    input_type=_REQUESTTYPE2,
    output_type=_RETURNTYPE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE1)

DESCRIPTOR.services_by_name['Service1'] = _SERVICE1


_SERVICE2 = _descriptor.ServiceDescriptor(
  name='Service2',
  full_name='unforgetable.Service2',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=348,
  serialized_end=498,
  methods=[
  _descriptor.MethodDescriptor(
    name='function1',
    full_name='unforgetable.Service2.function1',
    index=0,
    containing_service=None,
    input_type=_REQUESTTYPE1,
    output_type=_RETURNTYPE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='function2',
    full_name='unforgetable.Service2.function2',
    index=1,
    containing_service=None,
    input_type=_REQUESTTYPE2,
    output_type=_RETURNTYPE1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE2)

DESCRIPTOR.services_by_name['Service2'] = _SERVICE2

# @@protoc_insertion_point(module_scope)
